#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DijiWalk.Mobile.Droid.Resource", IsApplication=true)]

namespace DijiWalk.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int ListViewHighlighted = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ListViewSelected = 2130771969;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int camera = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int chat = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cup = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int en_cours = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int finis = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int gamepad = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int iconclose = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int jeux1 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int logo = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int monument = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int profil = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int quizz = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int signin = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int step = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int valider = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F070000
			public const int file_paths = 2131165184;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
